<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://parkingonstreet.herokuapp.com/whereiam/" />
<title>TESTsuite</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">TESTsuite</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//div[3]/a/span</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_username</td>
	<td>00000</td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_email</td>
	<td>aasassasasas</td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password1</td>
	<td>11111111</td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password2</td>
	<td>aaaaaaaa</td>
</tr>
<tr>
	<td>click</td>
	<td>css=input.btn.btn-primary</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_email</td>
	<td>mithilachwdhry@gmail.com</td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password1</td>
	<td>test</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=input.btn.btn-primary</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password2</td>
	<td>test</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=input.btn.btn-primary</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password2</td>
	<td>test</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=input.btn.btn-primary</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password1</td>
	<td>mith</td>
</tr>
<tr>
	<td>type</td>
	<td>id=id_password2</td>
	<td>mith</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>css=input.btn.btn-primary</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>
